global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 's3analyser'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 's3rawanalyser'
    metrics_path: '/s3-metrics.prom'
    static_configs:
      - targets: ['localhost:8000']